/*
 * NewJFrame.java
 *
 * Created on 15 de Dezembro de 2008, 20:52
 */

package br.ucam.kuabaSubsystem.gui;


import javax.swing.JList;

import br.ucam.kuabaSubsystem.controller.ArgumentController;
import br.ucam.kuabaSubsystem.controller.ViewRenderer;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author  pf_robo
 */
public class NewArgument extends JDialog {
    private ArgumentController controller;
    /** Creates new form NewJFrame */
    public NewArgument(ArgumentController controller) {
        initComponents();
        this.setModal(true);
        this.controller = controller;       
        this.argumentList.setModel(this.controller.allArguments());      
        
        //this.jLabel6.setText(this.controller.getIdea();
    }   
    public void setArgumentListLabel(String text){
        this.ArgumentsListLabel.setText(text);
    }
    @Override
    public void setVisible(boolean b) {
    	ViewRenderer.block();
        super.setVisible(b);        
    }
    public void setIdeaText(String text){
        this.ideaTextLabel.setText(text);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        argumentTextArea = new javax.swing.JTextArea();
        addArgument = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        argumentList = new javax.swing.JList();
        ArgumentsListLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ideaTextLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Arguments Edition");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        argumentTextArea.setColumns(20);
        argumentTextArea.setRows(5);
        argumentTextArea.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane3.setViewportView(argumentTextArea);

        addArgument.setText("Add");
        addArgument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addArgumentActionPerformed(evt);
            }
        });

        argumentList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        argumentList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                argumentListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(argumentList);

        ArgumentsListLabel.setText("Arguments List");

        //jLabel5.setText("Arguments for:");

        ideaTextLabel.setText("Idea Text Here");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                        .addComponent(addArgument, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ArgumentsListLabel)
                            .addGap(145, 145, 145))
                        .addComponent(jScrollPane1))
                    .addComponent(jLabel5)
                    .addComponent(ideaTextLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ideaTextLabel)
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addArgument)
                .addGap(18, 18, 18)
                .addComponent(ArgumentsListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addArgumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addArgumentActionPerformed
        String argumentText = "";
        argumentText = this.argumentTextArea.getText();
        if(argumentText.equals("")){
            JOptionPane.showMessageDialog(
                    this, "Please digit a valid argument", "Invalid Argument",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }            
        this.controller.newArgument(argumentText);    
        this.argumentTextArea.setText("");   
        this.argumentList.setModel(this.controller.allArguments());
        this.argumentTextArea.requestFocus();
    
}//GEN-LAST:event_addArgumentActionPerformed

private void argumentListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_argumentListMouseClicked
    if (evt.getClickCount() == 2) {
        JList list = (JList)evt.getSource();
         int index = list.locationToIndex(evt.getPoint());
         String item = (String)this.controller.getItem(index);
         this.argumentTextArea.setText("");
         this.argumentTextArea.setText(item);
    }
}//GEN-LAST:event_argumentListMouseClicked

private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    ViewRenderer.unblock();
    
}//GEN-LAST:event_formWindowClosing
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ArgumentsListLabel;
    private javax.swing.JButton addArgument;
    private javax.swing.JList argumentList;
    private javax.swing.JTextArea argumentTextArea;
    private javax.swing.JLabel ideaTextLabel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
    
}
