/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DRUnionRepositoryChooserPanel.java
 *
 * Created on 18/01/2012, 17:40:10
 */
package br.ucam.kuabaSubsystem.rationaleProcessor.unionui;

import br.ucam.kuabaSubsystem.core.KuabaSubsystem;
import br.ucam.kuabaSubsystem.repositories.KuabaRepository;
import br.ucam.kuabaSubsystem.repositories.RepositoryLoadException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Bruno
 */
public class DRUnionRepositoryChooserPanel extends javax.swing.JPanel {

    public static final String BASE_PROPERTY = "BASE_PROPERTY";
    
    private DefaultListModel<KuabaRepository> repositoryListModel;
    private KuabaRepository base;
    
    /** Creates new form DRUnionRepositoryChooserPanel */
    public DRUnionRepositoryChooserPanel() {
        initComponents();
        repositoryListModel = new DefaultListModel<KuabaRepository>();
        repositoryJList.setModel(repositoryListModel);
        base = null;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        repositoryJList = new javax.swing.JList();
        RepoListLabel = new javax.swing.JLabel();
        AddRepoFromFileButton = new javax.swing.JButton();
        AddRepoViaUrlButton = new javax.swing.JButton();
        RemoveButton = new javax.swing.JButton();
        setBaseButton = new javax.swing.JButton();
        baseLabel = new javax.swing.JLabel();

        jScrollPane1.setViewportView(repositoryJList);

        RepoListLabel.setText(org.openide.util.NbBundle.getMessage(DRUnionRepositoryChooserPanel.class, "DRUnionRepositoryChooserPanel.RepoListLabel.text")); // NOI18N

        AddRepoFromFileButton.setText(org.openide.util.NbBundle.getMessage(DRUnionRepositoryChooserPanel.class, "DRUnionRepositoryChooserPanel.AddRepoFromFileButton.text")); // NOI18N
        AddRepoFromFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRepoFromFileButtonActionPerformed(evt);
            }
        });

        AddRepoViaUrlButton.setText(org.openide.util.NbBundle.getMessage(DRUnionRepositoryChooserPanel.class, "DRUnionRepositoryChooserPanel.AddRepoViaUrlButton.text")); // NOI18N
        AddRepoViaUrlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRepoViaUrlButtonActionPerformed(evt);
            }
        });

        RemoveButton.setText(org.openide.util.NbBundle.getMessage(DRUnionRepositoryChooserPanel.class, "DRUnionRepositoryChooserPanel.RemoveButton.text")); // NOI18N
        RemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButtonActionPerformed(evt);
            }
        });

        setBaseButton.setText(org.openide.util.NbBundle.getMessage(DRUnionRepositoryChooserPanel.class, "DRUnionRepositoryChooserPanel.setBaseButton.text")); // NOI18N
        setBaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setBaseButtonActionPerformed(evt);
            }
        });

        baseLabel.setText(org.openide.util.NbBundle.getMessage(DRUnionRepositoryChooserPanel.class, "DRUnionRepositoryChooserPanel.baseLabel.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                    .addComponent(RepoListLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddRepoFromFileButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddRepoViaUrlButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(RemoveButton))
                    .addComponent(setBaseButton)
                    .addComponent(baseLabel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(RepoListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddRepoFromFileButton)
                    .addComponent(AddRepoViaUrlButton)
                    .addComponent(RemoveButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(setBaseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(baseLabel)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddRepoFromFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRepoFromFileButtonActionPerformed
        JFileChooser jfc = new JFileChooser();
        
        if (jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            KuabaRepository repo;
            try {
                String fName = jfc.getSelectedFile().getName();
                if(fName.endsWith(".xml") || fName.endsWith(".owl")) //verificando se é um arquivo owl ou zargo - precisa melhorar, pois utiliza a localização da KSE
                    repo = KuabaSubsystem.gateway.load(jfc.getSelectedFile().getAbsolutePath());
                else
                    repo = KuabaSubsystem.gateway.load("designRationale/"+fName+".xml");
                
                if (!repositoryListModel.contains(repo)) {
                    repositoryListModel.addElement(repo);
                    if (base == null) setBase(repo);
                } else
                    JOptionPane.showMessageDialog(this, "There is already a repository with the same base URL on the list.");
            } catch (RepositoryLoadException ex) {
                JOptionPane.showMessageDialog(this,ex.getMessage());
                Logger.getLogger(DRUnionRepositoryChooserPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
    }//GEN-LAST:event_AddRepoFromFileButtonActionPerformed

    private void AddRepoViaUrlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRepoViaUrlButtonActionPerformed
        String result = JOptionPane.showInputDialog(this,"Insert the Repository URL:","http://");
        if (result != null && !result.equals("http://")) {
            KuabaRepository repo;
            try {
                repo = KuabaSubsystem.gateway.load(result);
                if (!repositoryListModel.contains(repo)) {
                    repositoryListModel.addElement(repo);
                    if (base == null) setBase(repo);
                } else
                    JOptionPane.showMessageDialog(this, "There is already a repository with the same base URL on the list.");
            } catch (RepositoryLoadException ex) {
                JOptionPane.showMessageDialog(this,ex.getMessage());
                Logger.getLogger(DRUnionRepositoryChooserPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_AddRepoViaUrlButtonActionPerformed

    private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButtonActionPerformed
        // TODO add your handling code here:
        int[] selectedIndices = repositoryJList.getSelectedIndices();
        
        for (int x = 0; x<selectedIndices.length;x++) {
            if(repositoryListModel.get(selectedIndices[x]-x).equals(base)) 
                setBase(null);
            //remove must be after set base as null to trigger the event correctly
            repositoryListModel.remove(selectedIndices[x]-x).dispose();
        }  
    }//GEN-LAST:event_RemoveButtonActionPerformed

    private void setBaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setBaseButtonActionPerformed
        // TODO add your handling code here:
        int selection = repositoryJList.getSelectedIndex();
        
        if (selection >= 0) {
            KuabaRepository old = base;
            setBase(repositoryListModel.get(selection));
            firePropertyChange(BASE_PROPERTY, old, base);
        }
    }//GEN-LAST:event_setBaseButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddRepoFromFileButton;
    private javax.swing.JButton AddRepoViaUrlButton;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JLabel RepoListLabel;
    private javax.swing.JLabel baseLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList repositoryJList;
    private javax.swing.JButton setBaseButton;
    // End of variables declaration//GEN-END:variables

    public DefaultListModel<KuabaRepository> getRepositoryListModel() {
        return repositoryListModel;
    }
    
    public KuabaRepository getBaseRepository() {
        return base;
    }
    
    private void setBase(KuabaRepository newBase) {
        base = newBase;
        if (base != null) {
            baseLabel.setText("Current Base: "+base.getUrl());
        }
        else {
            baseLabel.setText("Current Base: Nothing");
        }
    }

}
