/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ucam.kuabaSubsystem.rationaleProcessor.unionui;

import java.awt.*;
import java.awt.event.*;
import java.util.*;
import javax.swing.*;
import javax.swing.border.*;

/**
 *
 * @author Bruno
 */

/**
 * This class is responsible for reacting to events generated by pushing any of the
 * three buttons, 'Next', 'Previous', and 'Cancel.' Based on what button is pressed,
 * the controller will update the model to show a new panel and reset the state of
 * the buttons as necessary.
 */
public class DRUnionWizardController implements ActionListener {


    
    private DRUnionWizard druWizard;
    
    /**
     * This constructor accepts a reference to the druWizard component that created it,
     * which it uses to update the button components and access the WizardModel.
     * @param w A callback to the druWizard component that created this controller.
     */    
    public DRUnionWizardController(DRUnionWizard w) {
        druWizard = w;
    }

    /**
     * Calling method for the action listener interface. This class listens for actions
     * performed by the buttons in the druWizard class, and calls methods below to determine
     * the correct course of action.
     * @param evt The ActionEvent that occurred.
     */    
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        
        if (evt.getActionCommand().equals(druWizard.CANCEL_BUTTON_ACTION_COMMAND))
            cancelButtonPressed();
        else if (evt.getActionCommand().equals(druWizard.BACK_BUTTON_ACTION_COMMAND))
            backButtonPressed();
        else if (evt.getActionCommand().equals(druWizard.NEXT_BUTTON_ACTION_COMMAND))
            nextButtonPressed();
        
    }
    
    
    
    private void cancelButtonPressed() {
        
        druWizard.close(druWizard.CANCEL_RETURN_CODE);
    }

    private void nextButtonPressed() {
 
        DRUnionWizardModel model = druWizard.getModel();
        DRUnionWizardPanelDescriptor descriptor = model.getCurrentPanelDescriptor();
        
        //  If it is a finishable panel, close down the dialog. Otherwise,
        //  get the ID that the current panel identifies as the next panel,
        //  and display it.
        
        Object nextPanelDescriptor = descriptor.getNextPanelDescriptor();
        
        if (nextPanelDescriptor instanceof DRUnionWizardPanelDescriptor.FinishIdentifier) {
            descriptor.aboutToHidePanel();
            druWizard.close(druWizard.FINISH_RETURN_CODE);
        } else {        
            druWizard.setCurrentPanel(nextPanelDescriptor);
        }
        
    }

    private void backButtonPressed() {
 
        DRUnionWizardModel model = druWizard.getModel();
        DRUnionWizardPanelDescriptor descriptor = model.getCurrentPanelDescriptor();
 
        //  Get the descriptor that the current panel identifies as the previous
        //  panel, and display it.
        
        Object backPanelDescriptor = descriptor.getBackPanelDescriptor();        
        druWizard.setCurrentPanel(backPanelDescriptor);
        
    }

    
    void resetButtonsToPanelRules() {
    
        //  Reset the buttons to support the original panel rules,
        //  including whether the next or back buttons are enabled or
        //  disabled, or if the panel is finishable.
        
        DRUnionWizardModel model = druWizard.getModel();
        DRUnionWizardPanelDescriptor descriptor = model.getCurrentPanelDescriptor();
        
        model.setCancelButtonText(druWizard.CANCEL_TEXT);
//        model.setCancelButtonIcon(druWizard.CANCEL_ICON);
        
        //  If the panel in question has another panel behind it, enable
        //  the back button. Otherwise, disable it.
        
        model.setBackButtonText(druWizard.BACK_TEXT);
//        model.setBackButtonIcon(druWizard.BACK_ICON);
        
        if (descriptor.getBackPanelDescriptor() != null)
            model.setBackButtonEnabled(Boolean.TRUE);
        else
            model.setBackButtonEnabled(Boolean.FALSE);

        //  If the panel in question has one or more panels in front of it,
        //  enable the next button. Otherwise, disable it.
 
        if (descriptor.getNextPanelDescriptor() != null)
            model.setNextFinishButtonEnabled(Boolean.TRUE);
        else
            model.setNextFinishButtonEnabled(Boolean.FALSE);
 
        //  If the panel in question is the last panel in the series, change
        //  the Next button to Finish. Otherwise, set the text back to Next.
        
        if (descriptor.getNextPanelDescriptor() instanceof DRUnionWizardPanelDescriptor.FinishIdentifier) {
            model.setNextFinishButtonText(druWizard.FINISH_TEXT);
//            model.setNextFinishButtonIcon(druWizard.FINISH_ICON);
        } else {
            model.setNextFinishButtonText(druWizard.NEXT_TEXT);
//            model.setNextFinishButtonIcon(druWizard.NEXT_ICON);
        }
        
    }
    
    
}
