/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DRUnionDecisionSetUpPanel.java
 *
 * Created on 21/01/2012, 21:00:44
 */
package org.argouml.module.kuabaModule.ui;

import br.ucam.kuabaSubsystem.graph.KuabaGraph;
import br.ucam.kuabaSubsystem.kuabaModel.Idea;
import br.ucam.kuabaSubsystem.repositories.KuabaRepository;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JInternalFrame;

/**
 *
 * @author Bruno
 */
public class DRViewPanel extends javax.swing.JPanel {

    private KuabaGraph kg = null;
    private JInternalFrame drGraph = null;
    private boolean subGraphMode = false;
    private Idea rootIdea;
    
    
    /** Creates new form DRUnionDecisionSetUpPanel */
    public DRViewPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jToggleButton1 = new javax.swing.JToggleButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jToggleButton2 = new javax.swing.JToggleButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(filler1);

        jToggleButton1.setText(org.openide.util.NbBundle.getMessage(DRViewPanel.class, "DRViewPanel.jToggleButton1.text")); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1);
        jPanel1.add(filler2);

        jToggleButton2.setText(org.openide.util.NbBundle.getMessage(DRViewPanel.class, "DRViewPanel.jToggleButton2.text")); // NOI18N
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton2);
        jPanel1.add(filler3);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        
        JInternalFrame graph;
        
        if(jToggleButton1.isSelected())
            graph = kg.generateIdeasGraph(false, false, !jToggleButton2.isSelected());
        else {
            if(subGraphMode)
                graph = kg.generateSubGraph(rootIdea, true, !jToggleButton2.isSelected());
            else
                graph = kg.generateFullGraph(false, true, false, !jToggleButton2.isSelected());
        }
        
        setDrGraph(graph);
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        
        jToggleButton1ActionPerformed(evt);
        
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables

    public void showFullDRView(KuabaRepository source) {
        subGraphMode = false;
        jToggleButton1.setEnabled(true);
        kg = new KuabaGraph(source);
        setDrGraph(kg.generateFullGraph(false,true,false,true));
    }
    
    public void showIdeaDRView(Idea idea) {
        subGraphMode = true;
        rootIdea = idea;
        jToggleButton1.setEnabled(false);
        kg = new KuabaGraph(rootIdea.getRepository());
        setDrGraph(kg.generateSubGraph(rootIdea, true, true));
    }
    
    private void setDrGraph(JInternalFrame newView) {
        if(drGraph != null)
            this.remove(drGraph);
        
        drGraph = newView;
        
        this.add(drGraph, BorderLayout.CENTER);
    }
}
