package br.ucam.kuabaSubsystem.kuabaModel;

//import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#Artifact
 *
 * @version generated on Sat Jun 21 10:48:19 BRT 2008
 */
public interface Artifact extends KuabaElement {

    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasCreationDate

    GregorianCalendar getHasCreationDate();

//    RDFProperty getHasCreationDateProperty();

    boolean hasHasCreationDate();

    void setHasCreationDate(GregorianCalendar newHasCreationDate);


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasDescription

    String getHasDescription();

//    RDFProperty getHasDescriptionProperty();

    boolean hasHasDescription();

    void setHasDescription(String newHasDescription);


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasName

    String getHasName();

//    RDFProperty getHasNameProperty();

    boolean hasHasName();

    void setHasName(String newHasName);


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasUrl

    String getHasUrl();

//    RDFProperty getHasUrlProperty();

    boolean hasHasUrl();

    void setHasUrl(String newHasUrl);


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#isCreatedBy

    Collection<Person> getIsCreatedBy();

//    RDFProperty getIsCreatedByProperty();

    boolean hasIsCreatedBy();

    Iterator<Person> listIsCreatedBy();

    void addIsCreatedBy(Person newIsCreatedBy);

    void removeIsCreatedBy(Person oldIsCreatedBy);

    void setIsCreatedBy(Collection<Person> newIsCreatedBy);


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#isDescribedBy

    Collection<FormalModel> getIsDescribedBy();

//    RDFProperty getIsDescribedByProperty();

    boolean hasIsDescribedBy();

    Iterator<FormalModel> listIsDescribedBy();

    void addIsDescribedBy(FormalModel newIsDescribedBy);

    void removeIsDescribedBy(FormalModel oldIsDescribedBy);

    void setIsDescribedBy(Collection<FormalModel> newIsDescribedBy);
}
