package br.ucam.kuabaSubsystem.kuabaModel;

//import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#CompositeArtifact
 *
 * @version generated on Sat Jun 21 10:48:19 BRT 2008
 */
public interface CompositeArtifact extends Artifact {

    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#compositionFunction

//    Collection getCompositionFunction();
//    
//    boolean hasCompositionFunction();
//
//    Iterator listCompositionFunction();
//
//    void addCompositionFunction(Object newCompositionFunction);
//
//    void removeCompositionFunction(Object oldCompositionFunction);
//
//    void setCompositionFunction(Collection newCompositionFunction);


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#compositionOf

    Collection<Artifact> getCompositionOf();

//    RDFProperty getCompositionOfProperty();

    boolean hasCompositionOf();

    Iterator<Artifact> listCompositionOf();

    void addCompositionOf(Artifact newCompositionOf);

    void removeCompositionOf(Artifact oldCompositionOf);

    void setCompositionOf(Collection<Artifact> newCompositionOf);


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#isVersionOf

    CompositeArtifact getIsVersionOf();

//    RDFProperty getIsVersionOfProperty();

    boolean hasIsVersionOf();

    void setIsVersionOf(CompositeArtifact newIsVersionOf);
}
