package br.ucam.kuabaSubsystem.kuabaModel;

//import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#ExpectedDuration
 *
 * @version generated on Sat Jun 21 10:48:19 BRT 2008
 */
public interface ExpectedDuration extends KuabaElement {
	
	public static String DAY = "day";
	public static String WEEK = "week";
	public static String MONTH = "month";
	public static String AGE = "age";
	public static String HOUR = "hour";
	public static String MINUTE = "minute";
		
    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasAmount

    int getHasAmount();

//    RDFProperty getHasAmountProperty();

    boolean hasHasAmount();

    void setHasAmount(int newHasAmount);


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasUnitTime

    Collection<String> getHasUnitTime();

//    RDFProperty getHasUnitTimeProperty();

    boolean hasHasUnitTime();

    Iterator<String> listHasUnitTime();

    void addHasUnitTime(String newHasUnitTime);

    void removeHasUnitTime(String oldHasUnitTime);

    void setHasUnitTime(Collection<String> newHasUnitTime);
}
