package br.ucam.kuabaSubsystem.kuabaModel;

//import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#FormalModel
 *
 * @version generated on Sat Jun 21 10:48:19 BRT 2008
 */
public interface FormalModel extends KuabaElement{
    
    public static final String UML_FORMAL_MODEL_ID = "UmlClass";

    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#describes

    Collection<Artifact> getDescribes();

//    RDFProperty getDescribesProperty();

    boolean hasDescribes();

    Iterator<Artifact> listDescribes();

    void addDescribes(Artifact newDescribes);

    void removeDescribes(Artifact oldDescribes);

    void setDescribes(Collection<Artifact> newDescribes);


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasLocalization

    Collection<String> getHasLocalization();

//    RDFProperty getHasLocalizationProperty();

    boolean hasHasLocalization();

    Iterator<String> listHasLocalization();

    void addHasLocalization(String newHasLocalization);

    void removeHasLocalization(String oldHasLocalization);

    void setHasLocalization(Collection<String> newHasLocalization);


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasName

    String getHasName();

//    RDFProperty getHasNameProperty();

    boolean hasHasName();

    void setHasName(String newHasName);


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#isPrescribedBy

    Collection<Method> getIsPrescribedBy();

//    RDFProperty getIsPrescribedByProperty();

    boolean hasIsPrescribedBy();

    Iterator<Method> listIsPrescribedBy();

    void addIsPrescribedBy(Method newIsPrescribedBy);

    void removeIsPrescribedBy(Method oldIsPrescribedBy);

    void setIsPrescribedBy(Collection<Method> newIsPrescribedBy);
}
