package br.ucam.kuabaSubsystem.kuabaModel;

//import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#Justification
 *
 * @version generated on Sat Jun 21 10:48:19 BRT 2008
 */
public interface Justification extends KuabaElement {

    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasText

    String getHasText();

//    RDFProperty getHasTextProperty();

    boolean hasHasText();

    void setHasText(String newHasText);


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#isDerivedOf

    Collection<Argument> getIsDerivedOf();

//    RDFProperty getIsDerivedOfProperty();

    boolean hasIsDerivedOf();

    Iterator<Argument> listIsDerivedOf();

    void addIsDerivedOf(Argument newIsDerivedOf);

    void removeIsDerivedOf(Argument oldIsDerivedOf);

    void setIsDerivedOf(Collection<Argument> newIsDerivedOf);
}
