package br.ucam.kuabaSubsystem.kuabaModel;

//import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#Method
 *
 * @version generated on Sat Jun 21 10:48:19 BRT 2008
 */
public interface Method extends KuabaElement {

    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#aggregates

    Collection<Activity> getAggregates();

//    RDFProperty getAggregatesProperty();

    boolean hasAggregates();

    Iterator<Activity> listAggregates();

    void addAggregates(Activity newAggregates);

    void removeAggregates(Activity oldAggregates);

    void setAggregates(Collection<Activity> newAggregates);


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasDescription

    String getHasDescription();

//    RDFProperty getHasDescriptionProperty();

    boolean hasHasDescription();

    void setHasDescription(String newHasDescription);


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasName

    String getHasName();

//    RDFProperty getHasNameProperty();

    boolean hasHasName();

    void setHasName(String newHasName);


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#prescribes

    Collection<FormalModel> getPrescribes();

//    RDFProperty getPrescribesProperty();

    boolean hasPrescribes();

    Iterator<FormalModel> listPrescribes();

    void addPrescribes(FormalModel newPrescribes);

    void removePrescribes(FormalModel oldPrescribes);

    void setPrescribes(Collection<FormalModel> newPrescribes);
}
