package br.ucam.kuabaSubsystem.kuabaModel;

//import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#Person
 *
 * @version generated on Sat Jun 21 10:48:19 BRT 2008
 */
public interface Person extends KuabaElement{

    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#creates

    Collection<Artifact> getCreates();    

    boolean hasCreates();

    Iterator<Artifact> listCreates();

    void addCreates(Artifact newCreates);

    void removeCreates(Artifact oldCreates);

    void setCreates(Collection<Artifact> newCreates);


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#executes

    Collection<Activity> getExecutes();   

    boolean hasExecutes();

    Iterator<Activity> listExecutes();

    void addExecutes(Activity newExecutes);

    void removeExecutes(Activity oldExecutes);

    void setExecutes(Collection<Activity> newExecutes);


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasAddress

    Collection<String> getHasAddress();    

    boolean hasHasAddress();

    Iterator<String> listHasAddress();

    void addHasAddress(String newHasAddress);

    void removeHasAddress(String oldHasAddress);

    void setHasAddress(Collection<String> newHasAddress);


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasName

    String getHasName();    

    boolean hasHasName();

    void setHasName(String newHasName);


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasTelephone

    Collection<String> getHasTelephone();    

    boolean hasHasTelephone();

    Iterator<String> listHasTelephone();

    void addHasTelephone(String newHasTelephone);

    void removeHasTelephone(String oldHasTelephone);

    void setHasTelephone(Collection<String> newHasTelephone);


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasEmail

    Collection<String> getHasEmail();    

    boolean hasHasEmail();

    Iterator<String> listHasEmail();

    void addHasEmail(String newHasEmail);

    void removeHasEmail(String oldHasEmail);

    void setHasEmail(Collection<String> newHasEmail);


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#makes

    Collection<Decision> getMakes();    

    boolean hasMakes();

    Iterator<Decision> listMakes();

    void addMakes(Decision newMakes);

    void removeMakes(Decision oldMakes);

    void setMakes(Collection<Decision> newMakes);


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#performs

    Collection<Role> getPerforms();
    
    boolean hasPerforms();

    Iterator<Role> listPerforms();

    void addPerforms(Role newPerforms);

    void removePerforms(Role oldPerforms);

    void setPerforms(Collection<Role> newPerforms);


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#presents

    Collection<ReasoningElement> getPresents();    

    boolean hasPresents();

    Iterator<ReasoningElement> listPresents();

    void addPresents(ReasoningElement newPresents);

    void removePresents(ReasoningElement oldPresents);

    void setPresents(Collection<ReasoningElement> newPresents);
}
