package br.ucam.kuabaSubsystem.kuabaModel;

//import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#ReasoningElement
 *
 * @version generated on Sat Jun 21 10:48:19 BRT 2008
 */
public interface ReasoningElement extends KuabaElement {

    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasCreationDate

	GregorianCalendar getHasCreationDate();

//    RDFProperty getHasCreationDateProperty();

    boolean hasHasCreationDate();

    void setHasCreationDate(GregorianCalendar newHasCreationDate);


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasText

    String getHasText();

//    RDFProperty getHasTextProperty();

    boolean hasHasText();

    void setHasText(String newHasText);


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#isInvolved

    Activity getIsInvolved();

//    RDFProperty getIsInvolvedProperty();

    boolean hasIsInvolved();

    void setIsInvolved(Activity newIsInvolved);


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#isPresentedBy

    Person getIsPresentedBy();

//    RDFProperty getIsPresentedByProperty();

    boolean hasIsPresentedBy();

    void setIsPresentedBy(Person newIsPresentedBy);


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#is_DefinedBy

    FormalModel getIsDefinedBy();

//    RDFProperty getIs_DefinedByProperty();

    boolean hasIsDefinedBy();

    void setIsDefinedBy(FormalModel newIsDefinedBy);


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#suggests

    Collection<Question> getSuggests();

//    RDFProperty getSuggestsProperty();

    boolean hasSuggests();

    Iterator<Question> listSuggests();

    void addSuggests(Question newSuggests);

    void removeSuggests(Question oldSuggests);

    void setSuggests(Collection<Question> newSuggests);
}
