package br.ucam.kuabaSubsystem.kuabaModel;

//import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#RelatedType
 *
 * @version generated on Sat Jun 21 10:48:19 BRT 2008
 */
public interface RelatedType extends KuabaElement {

    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasDestinationArtifact

    Collection<Artifact> getHasDestinationArtifact();

//    RDFProperty getHasDestinationArtifactProperty();

    boolean hasHasDestinationArtifact();

    Iterator<Artifact> listHasDestinationArtifact();

    void addHasDestinationArtifact(Artifact newHasDestinationArtifact);

    void removeHasDestinationArtifact(Artifact oldHasDestinationArtifact);

    void setHasDestinationArtifact(Collection<Artifact> newHasDestinationArtifact);


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasOriginArtifact

    Artifact getHasOriginArtifact();

//    RDFProperty getHasOriginArtifactProperty();

    boolean hasHasOriginArtifact();

    void setHasOriginArtifact(Artifact newHasOriginArtifact);


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasRelationType

    String getHasRelationType();

//    RDFProperty getHasRelationTypeProperty();

    boolean hasHasRelationType();

    void setHasRelationType(String newHasRelationType);
}
