package br.ucam.kuabaSubsystem.kuabaModel;

//import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#Role
 *
 * @version generated on Sat Jun 21 10:48:19 BRT 2008
 */
public interface Role extends KuabaElement{

    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasName

    String getHasName();

//    RDFProperty getHasNameProperty();

    boolean hasHasName();

    void setHasName(String newHasName);


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#isPerformedBy

    Collection<Person> getIsPerformedBy();

//    RDFProperty getIsPerformedByProperty();

    boolean hasIsPerformedBy();

    Iterator<Person> listIsPerformedBy();

    void addIsPerformedBy(Person newIsPerformedBy);

    void removeIsPerformedBy(Person oldIsPerformedBy);

    void setIsPerformedBy(Collection<Person> newIsPerformedBy);


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#isRequiredBy

    Collection<Activity> getIsRequiredBy();

//    RDFProperty getIsRequiredByProperty();

    boolean hasIsRequiredBy();

    Iterator<Activity> listIsRequiredBy();

    void addIsRequiredBy(Activity newIsRequiredBy);

    void removeIsRequiredBy(Activity oldIsRequiredBy);

    void setIsRequiredBy(Collection<Activity> newIsRequiredBy);
}
