package br.ucam.kuabaSubsystem.kuabaModel.impl;

import br.ucam.kuabaSubsystem.repositories.KuabaRepository;
import java.util.*;

import br.ucam.kuabaSubsystem.kuabaModel.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#RelatedType
 *
 * @version generated on Sat Jun 21 10:48:19 BRT 2008
 */
public class DefaultRelatedType extends DefaultKuabaElement implements RelatedType {

    public DefaultRelatedType(String id, KuabaRepository repo) {
        super(id, repo);
    }

    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasDestinationArtifact

    public Collection<Artifact> getHasDestinationArtifact() {
        return getObjectPropertyValues("hasDestinationArtifact");
    }

    public boolean hasHasDestinationArtifact() {
        return hasProperty("hasDestinationArtifact");
    }


    public Iterator<Artifact> listHasDestinationArtifact() {
        return getObjectPropertyValues("hasDestinationArtifact").iterator();
    }


    public void addHasDestinationArtifact(Artifact newHasDestinationArtifact) {
        addObjectPropertyValue("hasDestinationArtifact", newHasDestinationArtifact);
    }


    public void removeHasDestinationArtifact(Artifact oldHasDestinationArtifact) {
        removeObjectPropertyValue("hasDestinationArtifact", oldHasDestinationArtifact);
    }


    public void setHasDestinationArtifact(Collection<Artifact> newHasDestinationArtifact) {
        setObjectPropertyValues("hasDestinationArtifact", newHasDestinationArtifact);
    }



    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasOriginArtifact

    public Artifact getHasOriginArtifact() {
        Collection c = getObjectPropertyValues("hasOriginArtifact");
        if(c.isEmpty()) return null;
        return (Artifact) c.iterator().next();
    }

    public boolean hasHasOriginArtifact() {
        return hasProperty("hasOriginArtifact");
    }


    public void setHasOriginArtifact(Artifact newHasOriginArtifact) {
        Collection c = Collections.singleton(newHasOriginArtifact);
        setObjectPropertyValues("hasOriginArtifact", c);
    }



    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasRelationType

    public String getHasRelationType() {
        Collection<String> c = getDataPropertyValues("hasRelationType");
        if(c.isEmpty()) return null;
        return c.iterator().next();
    }

    public boolean hasHasRelationType() {
        return hasProperty("hasRelationType");
    }

    public void setHasRelationType(String newHasRelationType) {
        Collection c = Collections.singleton(newHasRelationType);
        setDataPropertyValues("hasRelationType", c);
    }
}
