package br.ucam.kuabaSubsystem.kuabaModel.impl;

import br.ucam.kuabaSubsystem.repositories.KuabaRepository;
import java.util.*;

import br.ucam.kuabaSubsystem.kuabaModel.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#FormalModel
 *
 * @version generated on Sat Jun 21 10:48:19 BRT 2008
 */
public class DefaultFormalModel extends DefaultKuabaElement implements FormalModel{

    public DefaultFormalModel(String id, KuabaRepository repo) {
        super(id, repo);
    }
    

    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#describes

    public Collection<Artifact> getDescribes() {
        return getObjectPropertyValues("describes");
    }

    public boolean hasDescribes() {
        return hasProperty("describes");
    }


    public Iterator<Artifact> listDescribes() {
        return getObjectPropertyValues("describes").iterator();
    }


    public void addDescribes(Artifact newDescribes) {
        addObjectPropertyValue("describes", newDescribes);
    }


    public void removeDescribes(Artifact oldDescribes) {
        removeObjectPropertyValue("describes", oldDescribes);
    }


    public void setDescribes(Collection<Artifact> newDescribes) {
        setObjectPropertyValues("describes", newDescribes);
    }



    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasLocalization

    public Collection<String> getHasLocalization() {
        return getDataPropertyValues("hasLocalization");
    }

    public boolean hasHasLocalization() {
        return hasProperty("hasLocalization");
    }


    public Iterator<String> listHasLocalization() {
        return getDataPropertyValues("hasLocalization").iterator();
    }


    public void addHasLocalization(String newHasLocalization) {
        addDataPropertyValue("hasLocalization", newHasLocalization);
    }


    public void removeHasLocalization(String oldHasLocalization) {
        removeDataPropertyValue("hasLocalization", oldHasLocalization);
    }


    public void setHasLocalization(Collection<String> newHasLocalization) {
        setDataPropertyValues("hasLocalization", newHasLocalization);
    }



    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasName

    public String getHasName() {
        Collection<String> c = getDataPropertyValues("hasName");
        if (c.isEmpty()) return null;
        return c.iterator().next();
    }

    public boolean hasHasName() {
        return hasProperty("hasName");
    }


    public void setHasName(String newHasName) {
        Collection c = Collections.singleton(newHasName);
        setDataPropertyValues("hasName", c);
    }



    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#isPrescribedBy

    public Collection<Method> getIsPrescribedBy() {
        return getObjectPropertyValues("isPrescribedBy");
    }

    public boolean hasIsPrescribedBy() {
        return hasProperty("isPrescribedBy");
    }


    public Iterator<Method> listIsPrescribedBy() {
        return getObjectPropertyValues("isPrescribedBy").iterator();
    }


    public void addIsPrescribedBy(Method newIsPrescribedBy) {
        addObjectPropertyValue("isPrescribedBy", newIsPrescribedBy);
    }


    public void removeIsPrescribedBy(Method oldIsPrescribedBy) {
        removeObjectPropertyValue("isPrescribedBy", oldIsPrescribedBy);
    }


    public void setIsPrescribedBy(Collection<Method> newIsPrescribedBy) {
        setObjectPropertyValues("isPrescribedBy", newIsPrescribedBy);
    }
}
