package br.ucam.kuabaSubsystem.kuabaModel.impl;

import br.ucam.kuabaSubsystem.repositories.KuabaRepository;

import java.text.ParseException;
import java.util.*;

import br.ucam.kuabaSubsystem.kuabaModel.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#Artifact
 *
 * @version generated on Sat Jun 21 10:48:19 BRT 2008
 */
public abstract class DefaultArtifact extends DefaultKuabaElement implements Artifact {

    public DefaultArtifact(String id, KuabaRepository repo) {
        super(id, repo);
    }


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasCreationDate

    public GregorianCalendar getHasCreationDate() {
    	Collection<String> c = getDataPropertyValues("hasCreationDate");
        if (c.isEmpty()) return null;
        
    	String date = c.iterator().next();
    	
        DateParser parser = new DateParser();
        GregorianCalendar gregorianFinishDate = null;
    	try {
    		gregorianFinishDate = parser.toGregorianCalendar(date);	
		} catch (ParseException e) {
			
			e.printStackTrace();
		}
		catch (NullPointerException npe) {
			return null;
		}
		
        return gregorianFinishDate;
    }


    public boolean hasHasCreationDate() {
        return hasProperty("hasCreationDate");
    }


    public void setHasCreationDate(GregorianCalendar newHasCreationDate) {
    	
        DateParser parser = new DateParser();
        
    	String xmlFormatedDate = parser.toStringFormat(newHasCreationDate);
        
        Collection c = Collections.singleton(xmlFormatedDate);
        setDataPropertyValues("hasCreationDate", c);
    }



    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasDescription

    public String getHasDescription() {
        Collection<String> c = getDataPropertyValues("hasDescription");
        if (c.isEmpty()) return null;
        return c.iterator().next();
    }

    public boolean hasHasDescription() {
        return hasProperty("hasDescription");
    }


    public void setHasDescription(String newHasDescription) {
        Collection c = Collections.singleton(newHasDescription);
        setDataPropertyValues("hasDescription", c);
    }



    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasName

    public String getHasName() {
        Collection<String> c = getDataPropertyValues("hasName");
        if (c.isEmpty()) return null;
        return c.iterator().next();
    }


    public boolean hasHasName() {
        return hasProperty("hasName");
    }


    public void setHasName(String newHasName) {
        Collection c = Collections.singleton(newHasName);
        setDataPropertyValues("hasName", c);
    }



    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasUrl

    public String getHasUrl() {
        Collection<String> c = getDataPropertyValues("hasUrl");
        if (c.isEmpty()) return null;
        return c.iterator().next();
    }


    public boolean hasHasUrl() {
        return hasProperty("hasUrl");
    }


    public void setHasUrl(String newHasUrl) {
        Collection c = Collections.singleton(newHasUrl);
        setDataPropertyValues("hasUrl", c);
    }



    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#isCreatedBy

    public Collection<Person> getIsCreatedBy() {
        return getObjectPropertyValues("isCreatedBy");
    }


    public boolean hasIsCreatedBy() {
        return hasProperty("isCreatedBy");
    }


    public Iterator<Person> listIsCreatedBy() {
        return getObjectPropertyValues("isCreatedBy").iterator();
    }


    public void addIsCreatedBy(Person newIsCreatedBy) {
        addObjectPropertyValue("isCreatedBy", newIsCreatedBy);
    }


    public void removeIsCreatedBy(Person oldIsCreatedBy) {
        removeObjectPropertyValue("isCreatedBy", oldIsCreatedBy);
    }


    public void setIsCreatedBy(Collection<Person> newIsCreatedBy) {
        setObjectPropertyValues("isCreatedBy", newIsCreatedBy);
    }



    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#isDescribedBy

    public Collection<FormalModel> getIsDescribedBy() {
        return getObjectPropertyValues("isDescribedBy");
    }

    public boolean hasIsDescribedBy() {
        return hasProperty("isDescribedBy");
    }


    public Iterator<FormalModel> listIsDescribedBy() {
        return getObjectPropertyValues("isDescribedBy").iterator();
    }


    public void addIsDescribedBy(FormalModel newIsDescribedBy) {
        addObjectPropertyValue("isDescribedBy", newIsDescribedBy);
    }


    public void removeIsDescribedBy(FormalModel oldIsDescribedBy) {
        removeObjectPropertyValue("isDescribedBy", oldIsDescribedBy);
    }


    public void setIsDescribedBy(Collection<FormalModel> newIsDescribedBy) {
        setObjectPropertyValues("isDescribedBy", newIsDescribedBy);
    }
}
