package br.ucam.kuabaSubsystem.kuabaModel.impl;

import br.ucam.kuabaSubsystem.repositories.KuabaRepository;
import java.util.*;

import br.ucam.kuabaSubsystem.kuabaModel.ExpectedDuration;




/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#ExpectedDuration
 *
 * @version generated on Sat Jun 21 10:48:19 BRT 2008
 */
public class DefaultExpectedDuration extends DefaultKuabaElement implements ExpectedDuration {

    public DefaultExpectedDuration(String id, KuabaRepository repo) {
        super(id, repo);
    }

    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasAmount

    public int getHasAmount() {
        Collection<String> c = getDataPropertyValues("hasAmount");
        if (c.isEmpty()) return -1;
        return Integer.parseInt(c.iterator().next());
    }

    public boolean hasHasAmount() {
        return hasProperty("hasAmount");
    }
    
    public void setHasAmount(int newHasAmount) {
        Collection c = Collections.singleton(String.valueOf(newHasAmount));
        setDataPropertyValues("hasAmount", c);
    }



    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasUnitTime

    public Collection<String> getHasUnitTime() {
        return getDataPropertyValues("hasUnitTime");
    }

    public boolean hasHasUnitTime() {
        return hasProperty("hasUnitTime");
    }


    public Iterator<String> listHasUnitTime() {
        return getDataPropertyValues("hasUnitTime").iterator();
    }


    public void addHasUnitTime(String newHasUnitTime) {
        addDataPropertyValue("hasUnitTime", newHasUnitTime);
    }


    public void removeHasUnitTime(String oldHasUnitTime) {
        removeDataPropertyValue("hasUnitTime", oldHasUnitTime);
    }


    public void setHasUnitTime(Collection<String> newHasUnitTime) {
        setDataPropertyValues("hasUnitTime", newHasUnitTime);
    }
}
