package br.ucam.kuabaSubsystem.kuabaModel.impl;

import br.ucam.kuabaSubsystem.repositories.KuabaRepository;
import java.util.*;

import br.ucam.kuabaSubsystem.kuabaModel.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#Person
 *
 * @version generated on Sat Jun 21 10:48:19 BRT 2008
 */
public class DefaultPerson extends DefaultKuabaElement implements Person {

    public DefaultPerson(String id, KuabaRepository repo) {
        super(id, repo);
    }


    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#creates

    public Collection<Artifact> getCreates() {
        return getObjectPropertyValues("creates");
    }

    public boolean hasCreates() {
        return hasProperty("creates");
    }

    public Iterator<Artifact> listCreates() {
        return getObjectPropertyValues("creates").iterator();
    }

    public void addCreates(Artifact newCreates) {
        addObjectPropertyValue("creates", newCreates);
    }

    public void removeCreates(Artifact oldCreates) {
        removeObjectPropertyValue("creates", oldCreates);
    }

    public void setCreates(Collection<Artifact> newCreates) {
        setObjectPropertyValues("creates", newCreates);
    }



    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#executes

    public Collection<Activity> getExecutes() {
        return getObjectPropertyValues("executes");
    }

    public boolean hasExecutes() {
        return hasProperty("executes");
    }


    public Iterator<Activity> listExecutes() {
        return getObjectPropertyValues("executes").iterator();
    }


    public void addExecutes(Activity newExecutes) {
        addObjectPropertyValue("executes", newExecutes);
    }


    public void removeExecutes(Activity oldExecutes) {
        removeObjectPropertyValue("executes", oldExecutes);
    }


    public void setExecutes(Collection<Activity> newExecutes) {
        setObjectPropertyValues("executes", newExecutes);
    }



    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasAddress

    public Collection<String> getHasAddress() {
        return getDataPropertyValues("hasAddress");
    }

    public boolean hasHasAddress() {
        return hasProperty("hasAddress");
    }

    public Iterator<String> listHasAddress() {
        return getDataPropertyValues("hasAddress").iterator();
    }


    public void addHasAddress(String newHasAddress) {
        addDataPropertyValue("hasAddress", newHasAddress);
    }


    public void removeHasAddress(String oldHasAddress) {
        removeDataPropertyValue("hasAddress", oldHasAddress);
    }


    public void setHasAddress(Collection<String> newHasAddress) {
        setDataPropertyValues("hasAddress", newHasAddress);
    }



    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasName

    public String getHasName() {
        Collection<String> c = getDataPropertyValues("hasName");
        if (c.isEmpty()) return null;
        return c.iterator().next();
    }
 
    public boolean hasHasName() {
        return hasProperty("hasName");
    }


    public void setHasName(String newHasName) {
        Collection c = Collections.singleton(newHasName);
        setDataPropertyValues("hasName", c);
    }
    

    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasTelephone

    public Collection<String> getHasTelephone() {
        return getDataPropertyValues("hasTelephone");
    }

    public boolean hasHasTelephone() {
        return hasProperty("hasTelephone");
    }

    public Iterator<String> listHasTelephone() {
        return getDataPropertyValues("hasTelephone").iterator();
    }

    public void addHasTelephone(String newHasTelephone) {
        addDataPropertyValue("hasTelephone", newHasTelephone);
    }

    public void removeHasTelephone(String oldHasTelephone) {
        removeDataPropertyValue("hasTelephone", oldHasTelephone);
    }

    public void setHasTelephone(Collection<String> newHasTelephone) {
        setDataPropertyValues("hasTelephone", newHasTelephone);
    }



    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasEmail

    public Collection<String> getHasEmail() {
        return getDataPropertyValues("hasEmail");
    }

    public boolean hasHasEmail() {
        return hasProperty("hasEmail");
    }


    public Iterator<String> listHasEmail() {
        return getDataPropertyValues("hasEmail").iterator();
    }


    public void addHasEmail(String newHasEmail) {
        addDataPropertyValue("hasEmail", newHasEmail);
    }


    public void removeHasEmail(String oldHasEmail) {
        removeDataPropertyValue("hasEmail", oldHasEmail);
    }


    public void setHasEmail(Collection<String> newHasEmail) {
        setDataPropertyValues("hasEmail", newHasEmail);
    }



    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#makes

    public Collection<Decision> getMakes() {
        return getObjectPropertyValues("makes");
    }

    public boolean hasMakes() {
        return hasProperty("makes");
    }


    public Iterator<Decision> listMakes() {
        return getObjectPropertyValues("makes").iterator();
    }


    public void addMakes(Decision newMakes) {
        addObjectPropertyValue("makes", newMakes);
    }


    public void removeMakes(Decision oldMakes) {
        removeObjectPropertyValue("makes", oldMakes);
    }


    public void setMakes(Collection<Decision> newMakes) {
        setObjectPropertyValues("makes", newMakes);
    }



    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#performs

    public Collection<Role> getPerforms() {
        return getObjectPropertyValues("performs");
    }

    public boolean hasPerforms() {
        return hasProperty("performs");
    }


    public Iterator<Role> listPerforms() {
        return getObjectPropertyValues("performs").iterator();
    }


    public void addPerforms(Role newPerforms) {
        addObjectPropertyValue("performs", newPerforms);
    }


    public void removePerforms(Role oldPerforms) {
        removeObjectPropertyValue("performs", oldPerforms);
    }


    public void setPerforms(Collection<Role> newPerforms) {
        setObjectPropertyValues("performs", newPerforms);
    }



    // Property http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#presents

    public Collection<ReasoningElement> getPresents() {
        return getObjectPropertyValues("presents");
    }

    public boolean hasPresents() {
        return hasProperty("presents");
    }


    public Iterator<ReasoningElement> listPresents() {
        return getObjectPropertyValues("presents").iterator();
    }


    public void addPresents(ReasoningElement newPresents) {
        addObjectPropertyValue("presents", newPresents);
    }


    public void removePresents(ReasoningElement oldPresents) {
        removeObjectPropertyValue("presents", oldPresents);
    }


    public void setPresents(Collection<ReasoningElement> newPresents) {
        setObjectPropertyValues("presents", newPresents);
    }
}
