package br.ucam.kuabaSubsystem.kuabaModel.impl;


import br.ucam.kuabaSubsystem.repositories.KuabaRepository;
//import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

import br.ucam.kuabaSubsystem.kuabaModel.Activity;
import br.ucam.kuabaSubsystem.kuabaModel.Argument;
import br.ucam.kuabaSubsystem.kuabaModel.Artifact;
import br.ucam.kuabaSubsystem.kuabaModel.AtomicArtifact;
import br.ucam.kuabaSubsystem.kuabaModel.CompositeArtifact;
import br.ucam.kuabaSubsystem.kuabaModel.Decision;
import br.ucam.kuabaSubsystem.kuabaModel.ExpectedDuration;
import br.ucam.kuabaSubsystem.kuabaModel.FormalModel;
import br.ucam.kuabaSubsystem.kuabaModel.Idea;
import br.ucam.kuabaSubsystem.kuabaModel.Justification;
import br.ucam.kuabaSubsystem.kuabaModel.KuabaEventPump;
import br.ucam.kuabaSubsystem.kuabaModel.KuabaModelFactory;
import br.ucam.kuabaSubsystem.kuabaModel.Method;
import br.ucam.kuabaSubsystem.kuabaModel.Person;
import br.ucam.kuabaSubsystem.kuabaModel.Question;
import br.ucam.kuabaSubsystem.kuabaModel.ReasoningElement;
import br.ucam.kuabaSubsystem.kuabaModel.RelatedType;
import br.ucam.kuabaSubsystem.kuabaModel.Role;
import br.ucam.kuabaSubsystem.kuabaModel.Solution;



/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 *
 * @version generated on Sat Jun 21 10:48:19 BRT 2008
 */
public class MyFactory implements KuabaModelFactory {

    public Idea createIdea(String id) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public Question createQuestion(String id) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public Argument createArgument(String id) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public Decision createDecision(String id) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public Role createRole(String id) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public AtomicArtifact createAtomicArtifact(String id) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public CompositeArtifact createCompositeArtifact(String id) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public ExpectedDuration createExpectedDuration(String id) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public RelatedType createRelatedType(String id) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public FormalModel createFormalModel(String id) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public Justification createJustification(String id) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public Person createPerson(String id) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public Activity createActivity(String id) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public Method createMethod(String id) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public KuabaRepository getKuabaRepository() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

//    private OWLModel owlModel;
//
//
//    public MyFactory(OWLModel owlModel) {
//        this.owlModel = owlModel;
//         
//    }
//
//
//    public RDFSNamedClass getIdeaClass() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#Idea";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFSNamedClass(name);
//    }
//
//    public Idea createIdea(String name) {
//    	name = name.toLowerCase();
//        final RDFSNamedClass cls = getIdeaClass();
//        Idea idea = (Idea) cls.createInstance(name).as(Idea.class);
//        if(idea != null)
//        	idea.setHasCreationDate(new GregorianCalendar());
//        KuabaEventPump.getInstance().notifyListerners(Idea.class, idea);
//        return idea;
//    }
//
//    public Idea getIdea(String name) {
//    	name = name.toLowerCase();
//        return owlModel.getRDFResource(name)!= null?(Idea) owlModel.getRDFResource(name).as(Idea.class):null ;
//    }
//
//    public Collection<Idea> getAllIdeaInstances() {
//        return getAllIdeaInstances(false);
//    }
//
//    public Collection<Idea> getAllIdeaInstances(boolean transitive) {
//        Collection<Idea> result = new ArrayList<Idea>();
//        final RDFSNamedClass cls = getIdeaClass();
//        RDFResource owlIndividual;
//        for (Iterator it = cls.getInstances(transitive).iterator();it.hasNext();) {
//            owlIndividual = (RDFResource) it.next();
//            result.add( (Idea) owlIndividual.as(Idea.class) );
//        }
//        return result;
//    }
//
//
//    public RDFSNamedClass getQuestionClass() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#Question";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFSNamedClass(name);
//    }
//
//    public Question createQuestion(String name) {
//    	name = name.toLowerCase();
//        final RDFSNamedClass cls = getQuestionClass();        
//        return (Question) cls.createInstance(name).as(Question.class);        
//    }
//
//    public Question getQuestion(String name) {
//    	name = name.toLowerCase();
//    	RDFResource resource = owlModel.getRDFResource(name); 
//    	if(resource != null)
//    		return (Question) resource.as(Question.class);
//    	return null;
//    }
//
//    public Collection<Question> getAllQuestionInstances() {
//        return getAllQuestionInstances(false);
//    }
//
//    public Collection<Question> getAllQuestionInstances(boolean transitive) {
//        Collection<Question> result = new ArrayList<Question>();
//        final RDFSNamedClass cls = getQuestionClass();
//        RDFResource owlIndividual;
//        for (Iterator it = cls.getInstances(transitive).iterator();it.hasNext();) {
//            owlIndividual = (RDFResource) it.next();
//            result.add( (Question) owlIndividual.as(Question.class) );
//        }
//        return result;
//    }
//
//
//    public RDFSNamedClass getArgumentClass() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#Argument";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFSNamedClass(name);
//    }
//
//    public Argument createArgument(String name) {
//    	name = name.toLowerCase();
//        final RDFSNamedClass cls = getArgumentClass();
//        return (Argument) cls.createInstance(name).as(Argument.class);
//    }
//
//    public Argument getArgument(String name) {
//    	name = name.toLowerCase();
//        return (Argument) owlModel.getRDFResource(name).as(Argument.class);
//    }
//
//    public Collection<Argument> getAllArgumentInstances() {
//        return getAllArgumentInstances(false);
//    }
//
//    public Collection<Argument> getAllArgumentInstances(boolean transitive) {
//        Collection<Argument> result = new ArrayList<Argument>();
//        final RDFSNamedClass cls = getArgumentClass();
//        RDFResource owlIndividual;
//        for (Iterator it = cls.getInstances(transitive).iterator();it.hasNext();) {
//            owlIndividual = (RDFResource) it.next();
//            result.add( (Argument) owlIndividual.as(Argument.class) );
//        }
//        return result;
//    }
//
//
//    public RDFSNamedClass getReasoningElementClass() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#ReasoningElement";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFSNamedClass(name);
//    }
//
//    public ReasoningElement createReasoningElement(String name) {
//    	name = name.toLowerCase();
//        final RDFSNamedClass cls = getReasoningElementClass();
//        return (ReasoningElement) cls.createInstance(name).as(ReasoningElement.class);
//    }
//
//    public ReasoningElement getReasoningElement(String name) {
//    	name = name.toLowerCase();
//        return (ReasoningElement) owlModel.getRDFResource(name).as(ReasoningElement.class);
//    }
//
//    public Collection<ReasoningElement> getAllReasoningElementInstances() {
//        return getAllReasoningElementInstances(false);
//    }
//
//    public Collection<ReasoningElement> getAllReasoningElementInstances(boolean transitive) {
//        Collection<ReasoningElement> result = new ArrayList<ReasoningElement>();
//        final RDFSNamedClass cls = getReasoningElementClass();
//        RDFResource owlIndividual;
//        for (Iterator it = cls.getInstances(transitive).iterator();it.hasNext();) {
//            owlIndividual = (RDFResource) it.next();
//            result.add( (ReasoningElement) owlIndividual.as(ReasoningElement.class) );
//        }
//        return result;
//    }
//
//
//    public RDFSNamedClass getRoleClass() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#Role";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFSNamedClass(name);
//    }
//
//    public Role createRole(String name) {
//    	name = name.toLowerCase();
//        final RDFSNamedClass cls = getRoleClass();
//        return (Role) cls.createInstance(name).as(Role.class);
//    }
//
//    public Role getRole(String name) {
//    	name = name.toLowerCase();
//        return (Role) owlModel.getRDFResource(name).as(Role.class);
//    }
//
//    public Collection<Role> getAllRoleInstances() {
//        return getAllRoleInstances(false);
//    }
//
//    public Collection<Role> getAllRoleInstances(boolean transitive) {
//        Collection<Role> result = new ArrayList<Role>();
//        final RDFSNamedClass cls = getRoleClass();
//        RDFResource owlIndividual;
//        for (Iterator it = cls.getInstances(transitive).iterator();it.hasNext();) {
//            owlIndividual = (RDFResource) it.next();
//            result.add( (Role) owlIndividual.as(Role.class) );
//        }
//        return result;
//    }
//
//
//    public RDFSNamedClass getAtomicArtifactClass() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#AtomicArtifact";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFSNamedClass(name);
//    }
//
//    public AtomicArtifact createAtomicArtifact(String name) {
//    	name = name.toLowerCase();
//        final RDFSNamedClass cls = getAtomicArtifactClass();
//        return (AtomicArtifact) cls.createInstance(name).as(AtomicArtifact.class);
//    }
//
//    public AtomicArtifact getAtomicArtifact(String name) {
//    	name = name.toLowerCase();
//        return (AtomicArtifact) owlModel.getRDFResource(name).as(AtomicArtifact.class);
//    }
//
//    public Collection<AtomicArtifact> getAllAtomicArtifactInstances() {
//        return getAllAtomicArtifactInstances(false);
//    }
//
//    public Collection<AtomicArtifact> getAllAtomicArtifactInstances(boolean transitive) {
//        Collection<AtomicArtifact> result = new ArrayList<AtomicArtifact>();
//        final RDFSNamedClass cls = getAtomicArtifactClass();
//        RDFResource owlIndividual;
//        for (Iterator it = cls.getInstances(transitive).iterator();it.hasNext();) {
//            owlIndividual = (RDFResource) it.next();
//            result.add( (AtomicArtifact) owlIndividual.as(AtomicArtifact.class) );
//        }
//        return result;
//    }
//
//
//    public RDFSNamedClass getArtifactClass() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#Artifact";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFSNamedClass(name);
//    }
//
//    public Artifact createArtifact(String name) {
//    	name = name.toLowerCase();
//        final RDFSNamedClass cls = getArtifactClass();
//        return (Artifact) cls.createInstance(name).as(Artifact.class);
//    }
//
//    public Artifact getArtifact(String name) {
//    	name = name.toLowerCase();
//        return (Artifact) owlModel.getRDFResource(name).as(Artifact.class);
//    }
//
//    public Collection<Artifact> getAllArtifactInstances() {
//        return getAllArtifactInstances(false);
//    }
//
//    public Collection<Artifact> getAllArtifactInstances(boolean transitive) {
//        Collection<Artifact> result = new ArrayList<Artifact>();
//        final RDFSNamedClass cls = getArtifactClass();
//        RDFResource owlIndividual;
//        for (Iterator it = cls.getInstances(transitive).iterator();it.hasNext();) {
//            owlIndividual = (RDFResource) it.next();
//            result.add( (Artifact) owlIndividual.as(Artifact.class) );
//        }
//        return result;
//    }
//
//
//    public RDFSNamedClass getExpectedDurationClass() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#ExpectedDuration";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFSNamedClass(name);
//    }
//
//    public ExpectedDuration createExpectedDuration(String name) {
//    	name = name.toLowerCase();
//        final RDFSNamedClass cls = getExpectedDurationClass();
//        return (ExpectedDuration) cls.createInstance(name).as(ExpectedDuration.class);
//    }
//
//    public ExpectedDuration getExpectedDuration(String name) {
//    	name = name.toLowerCase();
//    	if(owlModel.getRDFResource(name)==null)
//    		return null;
//        return (ExpectedDuration) owlModel.getRDFResource(name).as(ExpectedDuration.class);
//    }
//
//    public Collection<ExpectedDuration> getAllExpectedDurationInstances() {
//        return getAllExpectedDurationInstances(false);
//    }
//
//    public Collection<ExpectedDuration> getAllExpectedDurationInstances(boolean transitive) {
//        Collection<ExpectedDuration> result = new ArrayList<ExpectedDuration>();
//        final RDFSNamedClass cls = getExpectedDurationClass();
//        RDFResource owlIndividual;
//        for (Iterator it = cls.getInstances(transitive).iterator();it.hasNext();) {
//            owlIndividual = (RDFResource) it.next();
//            result.add( (ExpectedDuration) owlIndividual.as(ExpectedDuration.class) );
//        }
//        return result;
//    }
//
//
//    public RDFSNamedClass getRelatedTypeClass() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#RelatedType";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFSNamedClass(name);
//    }
//
//    public RelatedType createRelatedType(String name) {
//    	name = name.toLowerCase();
//        final RDFSNamedClass cls = getRelatedTypeClass();
//        return (RelatedType) cls.createInstance(name).as(RelatedType.class);
//    }
//
//    public RelatedType getRelatedType(String name) {
//    	name = name.toLowerCase();
//        return (RelatedType) owlModel.getRDFResource(name).as(RelatedType.class);
//    }
//
//    public Collection<RelatedType> getAllRelatedTypeInstances() {
//        return getAllRelatedTypeInstances(false);
//    }
//
//    public Collection<RelatedType> getAllRelatedTypeInstances(boolean transitive) {
//        Collection<RelatedType> result = new ArrayList<RelatedType>();
//        final RDFSNamedClass cls = getRelatedTypeClass();
//        RDFResource owlIndividual;
//        for (Iterator it = cls.getInstances(transitive).iterator();it.hasNext();) {
//            owlIndividual = (RDFResource) it.next();
//            result.add( (RelatedType) owlIndividual.as(RelatedType.class) );
//        }
//        return result;
//    }
//
//
//    public RDFSNamedClass getFormalModelClass() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#FormalModel";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFSNamedClass(name);
//    }
//
//    public FormalModel createFormalModel(String name) {
//    	name = name.toLowerCase();
//        final RDFSNamedClass cls = getFormalModelClass();
//        return (FormalModel) cls.createInstance(name).as(FormalModel.class);
//    }
//
//    public FormalModel getFormalModel(String name) {
//    	name = name.toLowerCase();
//    	if(owlModel.getRDFResource(name) == null)
//    		return null;
//        return (FormalModel) owlModel.getRDFResource(name).as(FormalModel.class);
//    }
//
//    public Collection<FormalModel> getAllFormalModelInstances() {
//        return getAllFormalModelInstances(false);
//    }
//
//    public Collection<FormalModel> getAllFormalModelInstances(boolean transitive) {
//        Collection<FormalModel> result = new ArrayList<FormalModel>();
//        final RDFSNamedClass cls = getFormalModelClass();
//        RDFResource owlIndividual;
//        for (Iterator it = cls.getInstances(transitive).iterator();it.hasNext();) {
//            owlIndividual = (RDFResource) it.next();
//            result.add( (FormalModel) owlIndividual.as(FormalModel.class) );
//        }
//        return result;
//    }
//
//
//    public RDFSNamedClass getJustificationClass() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#Justification";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFSNamedClass(name);
//    }
//
//    public Justification createJustification(String name) {
//    	name = name.toLowerCase();
//        final RDFSNamedClass cls = getJustificationClass();
//        return (Justification) cls.createInstance(name).as(Justification.class);
//    }
//
//    public Justification getJustification(String name) {
//    	name = name.toLowerCase();
//        return (Justification) owlModel.getRDFResource(name).as(Justification.class);
//    }
//
//    public Collection<Justification> getAllJustificationInstances() {
//        return getAllJustificationInstances(false);
//    }
//
//    public Collection<Justification> getAllJustificationInstances(boolean transitive) {
//        Collection<Justification> result = new ArrayList<Justification>();
//        final RDFSNamedClass cls = getJustificationClass();
//        RDFResource owlIndividual;
//        for (Iterator it = cls.getInstances(transitive).iterator();it.hasNext();) {
//            owlIndividual = (RDFResource) it.next();
//            result.add( (Justification) owlIndividual.as(Justification.class) );
//        }
//        return result;
//    }
//
//
//    public RDFSNamedClass getPersonClass() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#Person";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFSNamedClass(name);
//    }
//
//    public Person createPerson(String name) {
//    	name = name.toLowerCase();
//        final RDFSNamedClass cls = getPersonClass();
//        return (Person) cls.createInstance(name).as(Person.class);
//    }
//
//    public Person getPerson(String name) {
//    	name = name.toLowerCase();
//        return (Person) owlModel.getRDFResource(name).as(Person.class);
//    }
//
//    public Collection<Person> getAllPersonInstances() {
//        return getAllPersonInstances(false);
//    }
//
//    public Collection<Person> getAllPersonInstances(boolean transitive) {
//        Collection<Person> result = new ArrayList<Person>();
//        final RDFSNamedClass cls = getPersonClass();
//        RDFResource owlIndividual;
//        for (Iterator it = cls.getInstances(transitive).iterator();it.hasNext();) {
//            owlIndividual = (RDFResource) it.next();
//            result.add( (Person) owlIndividual.as(Person.class) );
//        }
//        return result;
//    }
//
//
//    public RDFSNamedClass getActivityClass() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#Activity";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFSNamedClass(name);
//    }
//
//    public Activity createActivity(String name) {
//    	name = name.toLowerCase();
//        final RDFSNamedClass cls = getActivityClass();
//        return (Activity) cls.createInstance(name).as(Activity.class);
//    }
//
//    public Activity getActivity(String name) {
//    	name = name.toLowerCase();
//        return (Activity) owlModel.getRDFResource(name).as(Activity.class);
//    }
//
//    public Collection<Activity> getAllActivityInstances() {    	
//        return getAllActivityInstances(false);
//    }
//
//    public Collection<Activity> getAllActivityInstances(boolean transitive) {
//        Collection<Activity> result = new ArrayList<Activity>();
//        final RDFSNamedClass cls = getActivityClass();
//        RDFResource owlIndividual;
//        for (Iterator it = cls.getInstances(transitive).iterator();it.hasNext();) {
//            owlIndividual = (RDFResource) it.next();
//            result.add( (Activity) owlIndividual.as(Activity.class) );
//        }
//        return result;
//    }
//
//
//    public RDFSNamedClass getMethodClass() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#Method";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFSNamedClass(name);
//    }
//
//    public Method createMethod(String name) {
//    	name = name.toLowerCase();
//        final RDFSNamedClass cls = getMethodClass();
//        return (Method) cls.createInstance(name).as(Method.class);
//    }
//
//    public Method getMethod(String name) {
//    	name = name.toLowerCase();
//        return (Method) owlModel.getRDFResource(name).as(Method.class);
//    }
//
//    public Collection<Method> getAllMethodInstances() {
//        return getAllMethodInstances(false);
//    }
//
//    public Collection<Method> getAllMethodInstances(boolean transitive) {
//        Collection<Method> result = new ArrayList<Method>();
//        final RDFSNamedClass cls = getMethodClass();
//        RDFResource owlIndividual;
//        for (Iterator it = cls.getInstances(transitive).iterator();it.hasNext();) {
//            owlIndividual = (RDFResource) it.next();
//            result.add( (Method) owlIndividual.as(Method.class) );
//        }
//        return result;
//    }
//
//
//    public RDFSNamedClass getDecisionClass() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#Decision";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFSNamedClass(name);
//    }
//
//    public Decision createDecision(String name) {
//    	name = name.toLowerCase();
//        final RDFSNamedClass cls = getDecisionClass();
//        return (Decision) cls.createInstance(name).as(Decision.class);
//    }
//
//    public Decision getDecision(String name) {
//    	name = name.toLowerCase();
//        return owlModel.getRDFResource(name)!= null? 
//        		(Decision) owlModel.getRDFResource(name).as(Decision.class): null;
//    }
//
//    public Collection<Decision> getAllDecisionInstances() {
//        return getAllDecisionInstances(false);
//    }
//
//    public Collection<Decision> getAllDecisionInstances(boolean transitive) {
//        Collection<Decision> result = new ArrayList<Decision>();
//        final RDFSNamedClass cls = getDecisionClass();
//        RDFResource owlIndividual;
//        for (Iterator it = cls.getInstances(transitive).iterator();it.hasNext();) {
//            owlIndividual = (RDFResource) it.next();
//            result.add( (Decision) owlIndividual.as(Decision.class) );
//        }
//        return result;
//    }
//
//
//    public RDFSNamedClass getCompositeArtifactClass() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#CompositeArtifact";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFSNamedClass(name);
//    }
//
//    public CompositeArtifact createCompositeArtifact(String name) {
//    	name = name.toLowerCase();
//        final RDFSNamedClass cls = getCompositeArtifactClass();
//        return (CompositeArtifact) cls.createInstance(name).as(CompositeArtifact.class);
//    }
//
//    public CompositeArtifact getCompositeArtifact(String name) {
//    	name = name.toLowerCase();
//        return (CompositeArtifact) owlModel.getRDFResource(name).as(CompositeArtifact.class);
//    }
//
//    public Collection<CompositeArtifact> getAllCompositeArtifactInstances() {
//        return getAllCompositeArtifactInstances(false);
//    }
//
//    public Collection<CompositeArtifact> getAllCompositeArtifactInstances(boolean transitive) {
//        Collection<CompositeArtifact> result = new ArrayList<CompositeArtifact>();
//        final RDFSNamedClass cls = getCompositeArtifactClass();
//        RDFResource owlIndividual;
//        for (Iterator it = cls.getInstances(transitive).iterator();it.hasNext();) {
//            owlIndividual = (RDFResource) it.next();
//            result.add( (CompositeArtifact) owlIndividual.as(CompositeArtifact.class) );
//        }
//        return result;
//    }
//
//
//    public RDFProperty getHasUnitTimeProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasUnitTime";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getCompositionFunctionProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#compositionFunction";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getHas_EmailProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#has_Email";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getHasAddressProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasAddress";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getHasTelephoneProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasTelephone";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getHasTypeProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasType";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getHasLocalizationProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasLocalization";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getHasDateProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasDate";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getHasCreationDateProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasCreationDate";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getHasFinishDateProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasFinishDate";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getHasNameProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasName";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getHasDescriptionProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasDescription";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getHasRelationTypeProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasRelationType";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getHasAmountProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasAmount";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getHasUrlProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasUrl";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getIsAcceptedProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#isAccepted";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getHasStartDateProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasStartDate";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getHasTextProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasText";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getAddressProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#address";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getIsRequiredByProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#isRequiredBy";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getIsPerformedByProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#isPerformedBy";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getObjectsToProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#objectsTo";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getIsInvolvedProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#isInvolved";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getIsPresentedByProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#isPresentedBy";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getHasDestinationArtifactProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasDestinationArtifact";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getHasOriginArtifactProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasOriginArtifact";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getIsAddressedByProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#isAddressedBy";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getInvolvesProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#involves";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getRequiresProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#requires";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getIsExecutedByProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#isExecutedBy";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getIsMadeByProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#isMadeBy";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getConcludesProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#concludes";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getCompositionOfProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#compositionOf";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getAggregatesProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#aggregates";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getPresentsProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#presents";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getInFavorOfProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#inFavorOf";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getPerformsProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#performs";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getPrescribesProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#prescribes";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getIsPrescribedByProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#isPrescribedBy";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getSuggestsProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#suggests";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getIsSuggestedByProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#isSuggestedBy";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getExecutesProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#executes";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getIsCreatedByProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#isCreatedBy";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getCreatesProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#creates";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getMakesProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#makes";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getIsConcludedByProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#isConcludedBy";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getHasArgumentProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasArgument";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getHasDecisionProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasDecision";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getIsDerivedOfProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#isDerivedOf";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getIsDescribedByProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#isDescribedBy";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getDescribesProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#describes";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getResultsInProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#resultsIn";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getHasJustificationProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasJustification";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getIs_DefinedByProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#is_DefinedBy";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getHasExpectedDurationProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#hasExpectedDuration";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getIsVersionOfProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#isVersionOf";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public RDFProperty getConsidersProperty() {
//        final String uri = "http://www.tecweb.inf.puc-rio.br/DesignRationale/KuabaOntology.owl#considers";
//        final String name = owlModel.getResourceNameForURI(uri);
//        return owlModel.getRDFProperty(name);
//    }
//
//
//    public OWLModel getOwlModel() {
//        return owlModel;
//    }
//
//    public KuabaRepository getKuabaRepository() {
//        throw new UnsupportedOperationException("Not supported yet.");
//    }

    public Solution createSolution(String id) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
	
}
